### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by defunctl**
Alright, turns out I was trying to solve the wrong problem.

This issue all has to do with https://github.com/hirak/prestissimo and https://github.com/ffraenz/private-composer-installer.

The solution was to set the `PluginEvents::PRE_FILE_DOWNLOAD    => [ 'injectPlaceholders', -2 ],` to run before (-2) either of their hooks and now all is good and both other packages appear to function as normal.

So I reverted much of the code, added some additional error checking in the URL fetching and cleaned up the comments.

### CODE REVIEW

**Comment by defunctl** [comment]
Hold up on merging this, there's still issues with using this and https://github.com/ffraenz/private-composer-installer together. I think we're going to have to use different place holders so it doesn't fire off  private-composer-installer's logic as well.

**Comment by mihkeleidast** [comment]
If possible, I would remove the placeholder replacing in here completely and use `ffraenz/private-composer-installer` for that. So this package would only deal with fetching the correct download url from GF API.

**Comment by defunctl** [comment]
And make private composer installer a dependency?

**Comment by defunctl** [comment]
The main issue here is https://github.com/hirak/prestissimo, when it does preload fetching to speed things up, the URL is not being replaced and composer downloads the HTML of the Gravity Forms API as a zip. v1.1.0 as of now actually sets the AWS URL in the lock file, which we obviously don't want. It was something we didn't notice for a day because the URL expired.

**Comment by mihkeleidast** [comment]
> And make private composer installer a dependency?

yup, that's exactly what i meant :)

**Comment by mihkeleidast** [comment]
Can you mark the PR as draft until it's mostly ready?

**Comment by defunctl** [comment]
> Can you mark the PR as draft until it's mostly ready?

I don't think you can change it to a draft once it's set to ready: https://github.community/t5/How-to-use-Git-and-GitHub/Feature-Request-Switch-from-ready-to-draft-in-pull-requests/td-p/19107

How about I @ you when ready, or I can close this and open it back up?

**Comment by defunctl** [comment]
I'll just close it for now, and open it once we've got it working and tested. Thanks!

**Pull request closed without merging**
