### PR TITLE
Fix missing changes for ffraenz/private-composer-installer v5

### PR DESCRIPTION
**Pull request by dsturm**
There have been several renames and structural changes in ffraenz/private-composer-installer v5 to be compatible with Composer v2, that have not been considered in #9.

So this PR fixes the issues from #10, where the installation of GF fails, because the dist url was not overriden.

### CODE REVIEW

**Comment by faahim** [comment]
Thanks so much, @dsturm for the fix! 🎉 

Can this be merged, please please, please? We're unable to install GravityForm for #10 atm.

**Comment by mihkeleidast** [comment]
It's been a long day so I'm a bit tired and can't figure out how to test this... Since I merged the previous PR without testing and it turned out to be broken, I'm reluctant to merge this without verifying the changes.

Currently I've tried the following:
1. Add the fork with the fix as a vcs repo:
```
    {
      "type": "vcs",
      "url": "https://github.com/zirkeldesign/gravityforms-composer-installer"
    }
```
2. Require the fork by adding `"gotoandplay/gravityforms-composer-installer": "dev-fix-private-composer-install-v5"` and running update
3. Add the GF package as repo that should use the same dev-* branch:
```
{
      "type": "package",
      "package": {
        "name": "gravityforms/gravityforms",
        "version": "2.4.21.3",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://www.gravityhelp.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=gravityforms&key={%WP_PLUGIN_GF_KEY}"
        },
        "require": {
          "composer/installers": "^1.4",
          "gotoandplay/gravityforms-composer-installer": "dev-fix-private-composer-install-v5"
        }
      }
    }
```
4. Require GF by running `composer require gravityforms/gravityforms`. This errors out.

What am I doing wrong and how did you test this yourself?

**Comment by dsturm** [comment]
Hej @mihkeleidast,

thanks for checking in. Yes, I'm sorry that my previous PR f**ked up - so I have great understanding that it should now be tested even more.

My tests were nearly the same:

1. Set up a new `roots/bedrock` project: `composer create-project roots/bedrock`
2. Add the fork with the fix as a vcs repo:
```json
    {
      "type": "vcs",
      "url": "https://github.com/zirkeldesign/gravityforms-composer-installer"
    }
```
3. Add `WP_PLUGIN_GF_KEY` key (and value) to `.env`
4. Add the GF package as repo that should use the forks dev-* branch:
```json
    {
      "type": "package",
      "package": {
        "name": "gravityforms/gravityforms",
        "version": "2.4.21.3",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://www.gravityhelp.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=gravityforms&key={%WP_PLUGIN_GF_KEY}"
        },
        "require": {
          "composer/installers": "^1.4",
          "gotoandplay/gravityforms-composer-installer": "dev-fix-private-composer-install-v5"
        }
      }
    }
```
5. Require GF by running `composer req gravityforms/gravityforms --no-cache`.

No errors on `Composer version 2.0.4 2020-10-30 22:39:11` and on `Composer version 1.10.17 2020-10-30 22:31:58`. What version are you using and what error occurs? Did you run `composer clear-cache`?

Even a `rm composer.lock && composer i -o` ran succesfully:

```sh
Loading composer repositories with package information
Updating dependencies
Lock file operations: 15 installs, 0 updates, 0 removals
  - Locking composer/installers (v1.9.0)
  - Locking ffraenz/private-composer-installer (v5.0.1)
  - Locking gotoandplay/gravityforms-composer-installer (dev-fix-private-composer-install-v5 4d0e2dd)
  - Locking gravityforms/gravityforms (2.4.21.3)
  - Locking oscarotero/env (v2.1.0)
  - Locking phpoption/phpoption (1.7.5)
  - Locking roave/security-advisories (dev-master 065a018)
  - Locking roots/bedrock-autoloader (1.0.3)
  - Locking roots/wordpress (5.5.1)
  - Locking roots/wordpress-core-installer (1.100.0)
  - Locking roots/wp-config (1.0.0)
  - Locking roots/wp-password-bcrypt (1.0.0)
  - Locking squizlabs/php_codesniffer (3.5.8)
  - Locking symfony/polyfill-ctype (v1.20.0)
  - Locking vlucas/phpdotenv (v4.1.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downloading roots/wordpress (5.5.1)
  - Upgrading roots/wordpress (5.5.1 5.5.1 => 5.5.1 ): Extracting archive
Generating optimized autoload files
9 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
---

The test / steps in summary
```sh
# Create roots/bedrock
composer create-project roots/bedrock test-gf-composer-v2
# Change to directory
cd test-gf-composer-v2
# Add fork
composer config repositories.gf-composer-v2 vcs https://github.com/zirkeldesign/gravityforms-composer-installer
# Add GF packages
composer config repositories.gf '{ "type": "package", "package": { "name": "gravityforms/gravityforms", "version": "2.4.21.3", "type": "wordpress-plugin", "dist": { "type": "zip", "url": "https://www.gravityhelp.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=gravityforms&key={%WP_PLUGIN_GF_KEY}" }, "require": { "composer/installers": "^1.4", "gotoandplay/gravityforms-composer-installer": "dev-fix-private-composer-install-v5" } } }'
# Add GF env key. Replace REPLACE_GF_KEY with your credentials
echo "
# Gravity Forms
WP_PLUGIN_GF_KEY='REPLACE_GF_KEY'" >> .env
# Source .env
source .env
# Require the GF package
composer req gravityforms/gravityforms
```

**Comment by mihkeleidast** [comment]
Okay yes, your steps of creating a new project worked, but I tried to do this in an existing project. Turns out, I did not have `"minimum-stability": "dev"` and `"prefer-stable": true` set in my config so it errored out because of that.

Verified this fix works in latest Composer@1 and Composer@2.

**Review by mihkeleidast — APPROVED** [review]

**Comment by mihkeleidast** [comment]
Released as 2.3.0

**Comment by dsturm** [comment]
Thanks @mihkeleidast !

**Pull request merged**
